version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing SAM CLI...
      - pip install aws-sam-cli

  build:
    commands:
      - echo Build started...
      - sam build --use-container

  post_build:
    commands:
      - echo Deploying application...
      - sam deploy --stack-name task-manager-api --region eu-west-1 --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - '*/'
