AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/create_task
      MemorySize: 128
      Timeout: 10
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post

  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/get_tasks
      MemorySize: 128
      Timeout: 10
      Events:
        GetTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/update_task
      MemorySize: 128
      Timeout: 10
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: put

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/delete_task
      MemorySize: 128
      Timeout: 10
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: delete

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/login
      MemorySize: 128
      Timeout: 10
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post
